services:
  _defaults:
    autowire: true
    public: true

  IvozProvider\Gearmand\Jobs\Xmlrpc:
    shared: false

  IvozProvider\Gearmand\Jobs\Recoder: ~

  Jobs\XmlrpcDelayed:
    class: IvozProvider\Gearmand\Jobs\Xmlrpc
    arguments: [ "sendXMLRPCDelayed" ]
