Ivoz\Provider\Domain\Model\QueueMember\QueueMemberAbstract:
  type: mappedSuperclass
  indexes:
    queueId:
      columns:
        - queueId
    userId:
      columns:
        - userId
  fields:
    penalty:
      type: integer
      nullable: true
      options:
        unsigned: false
  manyToOne:
    queue:
      targetEntity: \Ivoz\Provider\Domain\Model\Queue\QueueInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: members
      joinColumns:
        queueId:
          referencedColumnName: id
          onDelete: cascade
      orphanRemoval: false
    user:
      targetEntity: \Ivoz\Provider\Domain\Model\User\UserInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: queueMembers
      joinColumns:
        userId:
          referencedColumnName: id
          onDelete: cascade
      orphanRemoval: false
#  oneToOne:
#    astQueueMember:
#      targetEntity: \Ivoz\Ast\Domain\Model\QueueMember\QueueMemberInterface
#      cascade: {  }
#      fetch: LAZY
#      mappedBy: null
#      inversedBy: queueMember
#      joinColumns:
#        userId:
#          referencedColumnName: id
#          onDelete: cascade
#      orphanRemoval: false


